# This file was autogenerated by uv via the following command:
#    uv export --no-dev --no-hashes --no-editable -o requirements.txt
.
aiohappyeyeballs==2.6.1
    # via aiohttp
aiohttp==3.12.14
    # via food-crawling
aiosignal==1.4.0
    # via aiohttp
annotated-types==0.7.0
    # via pydantic
anyio==4.9.0
    # via
    #   httpx
    #   openai
async-timeout==5.0.1 ; python_full_version < '3.11'
    # via aiohttp
attrs==25.3.0
    # via aiohttp
beautifulsoup4==4.13.4
    # via bs4
bs4==0.0.2
    # via food-crawling
certifi==2025.7.14
    # via
    #   httpcore
    #   httpx
    #   requests
charset-normalizer==3.4.2
    # via requests
colorama==0.4.6 ; sys_platform == 'win32'
    # via tqdm
distro==1.9.0
    # via openai
exceptiongroup==1.3.0 ; python_full_version < '3.11'
    # via anyio
frozenlist==1.7.0
    # via
    #   aiohttp
    #   aiosignal
h11==0.16.0
    # via httpcore
httpcore==1.0.9
    # via httpx
httpx==0.28.1
    # via openai
idna==3.10
    # via
    #   anyio
    #   httpx
    #   requests
    #   yarl
jiter==0.10.0
    # via openai
multidict==6.6.3
    # via
    #   aiohttp
    #   yarl
openai==1.95.1
    # via food-crawling
propcache==0.3.2
    # via
    #   aiohttp
    #   yarl
pydantic==2.11.7
    # via openai
pydantic-core==2.33.2
    # via pydantic
python-dotenv==1.1.1
    # via food-crawling
pytz==2025.2
    # via food-crawling
requests==2.32.4
    # via food-crawling
sniffio==1.3.1
    # via
    #   anyio
    #   openai
soupsieve==2.7
    # via beautifulsoup4
tenacity==9.1.2
    # via food-crawling
tqdm==4.67.1
    # via openai
typing-extensions==4.14.1
    # via
    #   aiosignal
    #   anyio
    #   beautifulsoup4
    #   exceptiongroup
    #   multidict
    #   openai
    #   pydantic
    #   pydantic-core
    #   typing-inspection
typing-inspection==0.4.1
    # via pydantic
urllib3==2.5.0
    # via requests
yarl==1.20.1
    # via aiohttp
